INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (1,Elyse,Clunan,Teacher,12);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (2,Mia,Piperley,Janitor,12);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (3,Wes,Faulo,Janitor,8);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (4,Decca,Perrin,Canteen Staff,16);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (5,West,Climie,Student,5);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (6,Pauletta,Towne,Janitor,5);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (7,Adiana,O' Hanvey,Teacher,12);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (8,Devin,Kybird,Student,4);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (9,Lena,Clawley,Canteen Staff,3);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (10,Guy,Kruschev,Janitor,9);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (11,Isidor,Knowlys,Student,4);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (12,Durant,Bulpitt,Teacher,18);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (13,Roselle,Caldecutt,Janitor,5);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (14,Melosa,Vigars,Teacher,4);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (15,Theodore,Circuitt,Canteen Staff,9);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (16,Silvan,Madill,Canteen Staff,6);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (17,Cullan,Woolgar,Student,13);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (18,Raleigh,Cumbers,Teacher,19);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (19,Sher,Apdell,Canteen Staff,4);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (20,Cyndi,Thurlby,Janitor,4);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (21,Gun,Carnduff,Teacher,7);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (22,Elie,Cockin,Student,17);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (23,Farr,Jekel,Janitor,2);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (24,Yehudit,Porch,Canteen Staff,1);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (25,Tatiana,Heustice,Student,20);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (26,Khalil,Preto,Student,2);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (27,Lionello,Lauritsen,Canteen Staff,8);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (28,Magdalene,Face,Janitor,14);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (29,Darell,McKenny,Canteen Staff,14);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (30,Allin,Mariel,Student,12);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (31,Gwendolyn,Dowbakin,Student,8);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (32,Matti,Briamo,Teacher,9);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (33,Clo,Draysey,Student,17);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (34,Orlando,Menary,Janitor,16);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (35,Cassie,Baistow,Teacher,9);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (36,Ephrayim,Whewill,Janitor,13);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (37,Marie-jeanne,Millgate,Teacher,10);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (38,Seana,Couve,Teacher,6);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (39,Janene,Thomton,Canteen Staff,20);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (40,Hyacinthie,Salmon,Janitor,19);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (41,Ollie,Joule,Canteen Staff,16);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (42,Rock,Boskell,Janitor,5);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (43,Gonzales,Pinnocke,Teacher,3);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (44,Henrie,Redfern,Janitor,5);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (45,Pace,Inglefield,Canteen Staff,19);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (46,Trude,Lambertson,Student,8);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (47,Muhammad,Kmietsch,Student,10);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (48,Royce,Bagnold,Student,8);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (49,Gram,Crewdson,Janitor,1);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (50,Cammi,Matthews,Canteen Staff,1);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (51,Mari,Bandt,Teacher,14);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (52,Noel,Geary,Student,16);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (53,Launce,Vasilchikov,Janitor,13);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (54,Emelita,Gouldthorpe,Canteen Staff,9);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (55,Hymie,Bemlott,Canteen Staff,12);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (56,Court,Kimmings,Student,12);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (57,Anna-diana,Foard,Student,11);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (58,Joya,Van Oord,Canteen Staff,10);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (59,Clim,Helliwell,Teacher,15);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (60,Drucill,Fairtlough,Teacher,2);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (61,Frayda,Kyneton,Teacher,2);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (62,Jaquith,Croyden,Student,15);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (63,Charlena,Windous,Janitor,6);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (64,Ursula,Donet,Teacher,6);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (65,Orly,Atto,Canteen Staff,9);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (66,Maribel,Isakov,Janitor,11);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (67,Del,Dallmann,Canteen Staff,8);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (68,Sharron,Maffezzoli,Janitor,20);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (69,Bowie,Buey,Canteen Staff,8);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (70,Rivi,Cornewall,Teacher,4);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (71,Datha,Klawi,Canteen Staff,4);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (72,Phillida,Lisciandri,Student,3);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (73,Janella,Savoury,Janitor,2);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (74,Richardo,Fishbie,Teacher,5);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (75,Rod,Lundie,Canteen Staff,16);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (76,Shermie,Jayume,Student,11);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (77,Patty,Philipot,Janitor,19);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (78,Filippo,Jolley,Teacher,14);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (79,Florrie,Edgeon,Canteen Staff,20);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (80,Arthur,Stilling,Student,9);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (81,Zebulon,Kempston,Student,19);                                                                              
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (82,Andrey,Duffield,Canteen Staff,3);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (83,Johnna,Fawdry,Canteen Staff,14);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (84,Marissa,Mahaddie,Janitor,15);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (85,Dorey,Gribbins,Teacher,11);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (86,Sandor,Bogays,Student,4);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (87,Chevalier,Teggart,Teacher,20);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (88,Roxy,Couronne,Student,20);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (89,Willabella,Showt,Student,6);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (90,Kinny,Drew-Clifton,Janitor,12);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (91,Neils,Plampeyn,Canteen Staff,12);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (92,Silvain,Langland,Student,14);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (93,Tim,Wealleans,Canteen Staff,19);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (94,Tobias,Cardew,Janitor,14);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (95,Othelia,Harby,Canteen Staff,19);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (96,Yorgos,Swafield,Janitor,15);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (97,Tamarah,Lyard,Teacher,5);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (98,Adolphe,Benedikt,Student,4);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (99,Natale,Keuneke,Canteen Staff,4);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (100,Annamaria,Caldicott,Student,10);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (101,Imogen,Hacquel,Teacher,6);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (102,Gabie,Selman,Teacher,14);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (103,Bran,Hellwig,Canteen Staff,13);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (104,Spenser,Denziloe,Student,1);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (105,Jewel,Grolle,Janitor,3);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (106,Millisent,Goodinson,Student,8);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (107,Ashil,Sherwyn,Teacher,4);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (108,Sylvan,Woolliams,Teacher,10);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (109,Stafani,Strothers,Student,16);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (110,Wald,Grigolli,Janitor,14);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (111,Wade,Gildea,Teacher,6);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (112,Alford,Basler,Canteen Staff,10);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (113,Ham,Grimstead,Canteen Staff,8);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (114,Gawen,Ubsdall,Canteen Staff,13);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (115,Bessy,Empleton,Teacher,1);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (116,Etheline,Benoit,Janitor,6);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (117,Christy,Jellybrand,Janitor,14);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (118,Hayley,Dreng,Janitor,3);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (119,Aryn,Carr,Teacher,5);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (120,Gena,Rablan,Canteen Staff,18);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (121,Hilario,Gullan,Janitor,12);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (122,Ethelbert,Grassick,Student,11);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (123,Nani,Foxton,Student,4);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (124,Becky,Cass,Teacher,14);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (125,Vernice,Studdal,Teacher,6);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (126,Jason,Jillis,Canteen Staff,6);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (127,Christiane,McDarmid,Canteen Staff,14);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (128,Hodge,Shoebridge,Canteen Staff,11);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (129,Shannon,Coghlin,Student,19);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (130,Dal,Deinhard,Student,7);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (131,Barnett,Voice,Canteen Staff,8);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (132,Bellina,Dowrey,Canteen Staff,1);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (133,Aurelea,Bolden,Canteen Staff,2);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (134,Johannah,Bremeyer,Student,4);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (135,Gauthier,Tirte,Teacher,12);
INSERT INTO Customers (Customer_id,First_name,Last_name,Faculty,Limit) VALUES (136,Nerti,Kobu,Teacher,9);
